import data as dataBase

cnf = [
    [['K'],['K2 K3', 'K2 Pel', 'K2 K4', 'K2 K5', 'K2 K6', 'K2 O', 'K2 Ket', 'S P', 'S O']],
    [['K2'],['S P']],
    [['K3'],['Pel O']],
    [['K4'],['Pel Ket']],
    [['K5'],['O Ket']],
    [['K6'],['O Pel']],
    [['S'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'polih', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica', 'nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina', 'iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun'
, 'NP Noun', 'NP PropNoun', 'NP Pronoun', 'NP Verb', 'Adv NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'Adj NP', 'NP Adj']],
    [['P'],['memasak', 'mengerjakan', 'bertemu', 'mengirim', 'melaksanakan', 'memperbaiki', 'bermain', 'main', 'belajar', 'berkebun', 'bergandengan', 'pecah', 'tahan', 'mengeluarkan', 'bersalaman', 'mempresentasikan', 'mempelajari', 'menunjuk', 'melakukan', 'penangkapan', 'membawa', 'mengobrol', 'goreng', 'lukis', 'tersebut', 'berhenti', 'menangisi', 'merasa', 'berbicara', 'memperjelas', 'mengajar', 'menyimak', 'menari', 'menyimpulkan', 'memberikan', 'bantuan', 'mengajarkan', 'mulai', 'berenang', 'tidur', 'kedapatan', 'merokok', 'berada', 'mengucilkan', 'berangkat', 'mengambang', 'pergi', 'bersepeda', 'pulang', 'bekerja', 'datang', 'berkunjung', 'berbelanja', 'bersedia', 'membantu', 'bertamasya', 'kebutuhan', 'memutuskan', 'memotong', 'menggunakan', 'menanggapi', 'ikut', 'asalkan', 'turut', 'memerah', 'peternakan', 'memainkan', 'terlihat', 'memancing', 'mencukur', 'Adv VP', 'Verb NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'baru', 'singkat', 'keras', 'tua', 'hangat', 'baik', 'lama', 'miskin', 'santai', 'dekat', 'rapi', 'rapat', 'Adv Adj', 'VP Prep', 'Adj Verb', 'Verb Adj']],
    [['O'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'pakaryan', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica', 'nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina', 'iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun', 'NP Noun', 'NP PropNoun', 'NP Pronoun', 'NP Verb', 'Adv NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'Adj NP', 'NP Adj']],
    [['Pel'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'pakaryan', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica', 'nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina', 'iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun', 'NP Noun', 'NP PropNoun', 'NP Pronoun', 'NP Verb', 'Adv NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'Adj NP', 'NP Adj', 'mekarya', 'ngaryananing', 'mirengang', 'ngemolihang', 'muput', 'kaatur', 'numbasang', 'adung', 'lunga', 'malajah', 'naurin', 'nyatetin', 'mandakin', 'nyakan', 'ngetep', 'mabalih', 'numbas', 'megending', 'arep', 'kelas', 'maduwe', 'muput', 'karya', 'nyumu', 'palalianan', 'ngemolihang', 'kaevakuasi', 'ngardiang', 'ngaksi', 'rabin', 'mobot', 'makolem', 'nunas', 'usan', 'ngicenin', 'budal', 'micayang', 'maputra', 'Adv Adj', 'VP Prep', 'Adj Verb', 'Verb Adj', 'Prep Verb']],
    [['Ket'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'pakaryan', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica', 'nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina', 'iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun', 'NP Noun', 'NP PropNoun', 'NP Pronoun', 'NP Verb', 'Adv NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'Adj NP', 'NP Adj', 'mekarya', 'ngaryananing', 'mirengang', 'ngemolihang', 'muput', 'kaatur', 'numbasang', 'adung', 'lunga', 'malajah', 'naurin', 'nyatetin', 'mandakin', 'nyakan', 'ngetep', 'mabalih', 'numbas', 'megending', 'arep', 'kelas', 'maduwe', 'muput', 'karya', 'nyumu', 'palalianan', 'ngemolihang', 'kaevakuasi', 'ngardiang', 'ngaksi', 'rabin', 'mobot', 'makolem', 'nunas', 'usan', 'ngicenin', 'budal', 'micayang', 'maputra', 'Adv VP', 'Verb NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'baru', 'singkat', 'keras', 'tua', 'hangat', 'baik', 'lama', 'miskin', 'santai', 'dekat', 'rapi', 'rapat', 'Adv Adj', 'VP Prep', 'Adj Verb', 'Verb Adj', 'Prep Verb']],
    [['NP'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'pakaryan', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica', 'nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina', 'iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun', 'NP Noun', 'NP PropNoun', 'NP Pronoun', 'NP Verb', 'Adv NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'Adj NP', 'NP Adj']],
    [['VP'],['mekarya', 'ngaryananing', 'mirengang', 'ngemolihang', 'muput', 'kaatur', 'numbasang', 'adung', 'lunga', 'malajah', 'naurin', 'nyatetin', 'mandakin', 'nyakan', 'ngetep', 'mabalih', 'numbas', 'megending', 'arep', 'kelas', 'maduwe', 'muput', 'karya', 'nyumu', 'palalianan', 'ngemolihang', 'kaevakuasi', 'ngardiang', 'ngaksi', 'rabin', 'mobot', 'makolem', 'nunas', 'usan', 'ngicenin', 'budal', 'micayang', 'maputra', 'Adv VP', 'Verb NP', 'Prep NP', 'Prep Verb', 'Prep Adj', 'wawu', 'sampun', 'anyar', 'antengan', 'seneng', 'ageng', 'ramia', 'meneng', 'treptu', 'tiwas', 'sungkan', 'Adv Adj', 'VP Prep', 'Adj Verb', 'Verb Adj', 'Prep Verb']],
    [['PP'],['Prep NP', 'Prep Adj']],
    [['AdjP'],['Adv Adj', 'wawu', 'sampun', 'anyar', 'antengan', 'seneng', 'ageng', 'ramia', 'meneng', 'treptu', 'tiwas', 'sungkan']],
    [['Noun'],['aji', 'semengan', 'tugas', 'gendingan', 'kamarnyane', 'pakaryan', 'tugas', 'biang', 'sepatu', 'semeton', 'makesami', 'perusahaan', 'tegal', 'beburon', 'jinah', 'semester', 'bulane', 'benjang', 'penyadane', 'daftar', 'pakaryan', 'ajah-ajahan', 'nasi', 'goreng', 'carang', 'kayu', 'pabalihan', 'horor', 'kuaca', 'boneka', 'trewelu', 'matematika', 'bola', 'benjang', 'gajih', 'kantornyane', 'pangenah', 'agra', 'giri', 'korban', 'makesami', 'genah', 'parindikan', 'tu', 'biang', 'ajengan', 'bekel', 'adi', 'okan', 'dane', 'istri', 'taban', 'ibu', 'guru', 'sisiane', 'bapak', 'kepala', 'sekolah', 'pawarah-warah', 'aji', 'dumunan', 'ratu', 'peranda', 'sarenan', 'baler', 'pak', 'camat', 'wantuan', 'krama', 'dayu', 'mangkin', 'ica']],
    [['Pronoun'],['iraga', 'tiang', 'ragane', 'punika', 'nika', 'idane', 'ida', 'ipun']],
    [['Adv'],['kari', 'sane', 'jagi', 'patut', 'wikan', 'prasida', 'dados', 'nenten', 'durung', 'sampun', 'tur', 'kantun']],
    [['Adj'],['baru', 'singkat', 'keras', 'tua', 'hangat', 'baik', 'lama', 'miskin', 'santai', 'dekat', 'rapi', 'rapat']],
    [['PropNoun'],['nina', 'jeno', 'dito', 'jeno', 'gita', 'jeno', 'sinta', 'andi', 'rani', 'rina']],
    [['Prep'],['ring', 'ka', 'ke', 'para', 'majeng']],
    [['Verb'],['mekarya', 'ngaryananing', 'mirengang', 'ngemolihang', 'muput', 'kaatur', 'numbasang', 'adung', 'lunga', 'malajah', 'naurin', 'nyatetin', 'mandakin', 'nyakan', 'ngetep', 'mabalih', 'numbas', 'megending', 'arep', 'kelas', 'maduwe', 'muput', 'karya', 'nyumu', 'palalianan', 'ngemolihang', 'kaevakuasi', 'ngardiang', 'ngaksi', 'rabin', 'mobot', 'makolem', 'nunas', 'usan', 'ngicenin', 'budal', 'micayang', 'maputra']]
    ]
res = {}

def rule():
    for index, rule in enumerate(cnf):
        for step in range(1, len(cnf[index][1])):
            # print(cnf[index][1][i])
            key = cnf[index][1][step]
            j = step - 1 
            while j >= 0 and key < cnf[index][1][j]:
                cnf[index][1][j + 1] = cnf[index][1][j]
                j = j - 1
            cnf[index][1][j + 1] = key
    # for i in cnf:
    #     print(i)

    for i in cnf:
        for key in i[0]:
            res[key] = i[1]
            break
    # for i, j in res.items():
    #     print(i, j, end='\n\n')
    
    return res
def kamusCNF():
    dataBase.kamus(cnf)
